#!/bin/bash

SESSION_ID_ALL="
    cn us eu gg
    etcd1
    mq1 mq2 
    ticn tius tigg
    s-sh s-sz s-us
    yms1 yms2 yms3 
    21 22 23 
    31 32 33 
"

session_check() {
    case ${ID} in
        "cn")
            GROUP=dev
            ROLE=root
            IP=cn.ylmw.pp.ua
            ;;
        "us")
            GROUP=dev
            ROLE=root
            IP=us.ylmw.pp.ua
            ;;
        "eu")
            GROUP=dev
            ROLE=root
            IP=eu.ylmw.pp.ua
            ;;
        "gg")
            GROUP=dev
            ROLE=root
            IP=gg.ylmw.pp.ua
            ;;
        "etcd1")
            GROUP=sync
            ROLE=root
            IP=etcd1.l7i.top
            ;;
        "mq1")
            GROUP=sync
            ROLE=root
            IP=10.200.112.158
            ;;
        "mq2")
            GROUP=sync
            ROLE=root
            IP=10.200.112.159
            ;;
        "ticn")
            GROUP=sync
            ROLE=root
            IP=tidb-cn.l7i.top
            ;;
        "tius")
            GROUP=sync
            ROLE=root
            IP=tidb-us.l7i.top
            ;;
        "tigg")
            GROUP=sync
            ROLE=root
            IP=tidb-global.l7i.top
            ;;
        "s-sh")
            GROUP=sang
            ROLE=root
            IP=sh.sang.pp.ua
            ;;
        "s-sz")
            GROUP=sang
            ROLE=root
            IP=sz.sang.pp.ua
            ;;
        "s-us")
            GROUP=sang
            ROLE=root
            IP=us.sang.pp.ua
            ;;
        "yms1")
            GROUP=yms
            ROLE=root
            IP=10.83.1.73
            ;;
        "yms2")
            GROUP=yms
            ROLE=root
            IP=10.83.1.74
            ;;
        "yms3")
            GROUP=yms
            ROLE=root
            IP=10.83.1.75
            ;;
        "21")
            GROUP=
            ROLE=root
            IP=10.71.6.10
            ;;
        "22")
            GROUP=
            ROLE=root
            IP=10.71.6.11
            ;;
        "23")
            GROUP=
            ROLE=root
            IP=10.71.6.13
            ;;
        "31")
            GROUP=
            ROLE=root
            IP=10.200.112.195
            ;;
        "32")
            GROUP=
            ROLE=root
            IP=10.200.112.74
            ;;
        "33")
            GROUP=
            ROLE=root
            IP=10.200.112.119
            ;;
    esac
}

# ==============================================================================

session_info() {
    session_check
    echo -e "[group: ${GROUP}]\t\t[id: ${ID}]\t\t[role: ${ROLE}]\t\t[ip: ${IP}]"
}

session_info_all() {
    for ID in ${SESSION_ID_ALL}
    do
        session_check
        session_info
    done
}

session_conn() {
    session_check
    ssh ${ROLE}@${IP}
}

session_help() {
    echo "usage: $0 [list | help | sessionId]"
    echo ""
}

if [ $# -eq 0 ]; then
    session_help
    session_info_all
else
    case $1 in
        "list")
            if [ ! -z $2 ]; then
                ID=$2
                session_info
            else
                session_info_all
            fi
            ;;
        "help")
            session_help
            ;;
        *)
            ID=$1
            session_conn $1
    esac
fi
