#!/bin/bash

LIST_PATH=ssh.list

ssh_conn() {
    ID=$1
    USER=`awk -F' ' '{if($2==1.1) print $8}' $LIST_PATH`
    ADDR=`awk -F' ' '{if($2==1.1) print $6}' $LIST_PATH`
    ssh ${USER}@${ADDR}
}

case "$1" in
    "--help"|"-h")
        echo "usage: $ sessionId/sessionAliasName"
        ;;
    "--list"|"-l")
        cat $LIST_PATH
        ;;
    *)
        if [ $# -lt 1 ]; then
            $0 --help
            $0 --list
        else
            ssh_conn
        fi
        ;;
esac


