version: '2'

services:
  db:
    image: mariadb:10.1
    container_name: filerun-db
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    ports:
      - "3306:3306"
    volumes:
      - /data/filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8081:80"
    volumes:
      - /data/filerun/html:/var/www/html
      - /mnt:/user-files/mnt
