log:
  level: DEBUG

metrics:
  addr: 0.0.0.0:9475

clusters:
  sang:
    enable: true
    namesrvaddrs:
      - 10.120.24.130:9876
      - 10.120.26.60:9876
    intervalsec: 1
    timeoutsec: 1
    monitors:
      - topic: EXAMPLE_TOPIC
        consumergroup:
          mode: whitelist
          blacklist:
          whitelist:
            - EXAMPLE_CONSUMER_GROUP
        tolerance:
          offset: 0
          timesec: 0
        fakemsg:
          enable: false
          waitsec:
          body:
          properties:
